application: tgt-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "0d 0h 0m 5s"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app

- url: /reminder
  script: main.app
  login: admin

libraries:
- name: jinja2
  version: latest
